// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1TlXwSxiiuk73g0zDsAuTvWgetmskJs',
    appId: '1:694288625915:web:2b6c542dbb3d763a1ec05e',
    messagingSenderId: '694288625915',
    projectId: 'quizapp-35d28',
    authDomain: 'quizapp-35d28.firebaseapp.com',
    storageBucket: 'quizapp-35d28.appspot.com',
    measurementId: 'G-YPM2PM0RGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVy24CB_A_j_23D3P6PW9RljY2zb5YpTw',
    appId: '1:694288625915:android:6115a7c045dad1f61ec05e',
    messagingSenderId: '694288625915',
    projectId: 'quizapp-35d28',
    storageBucket: 'quizapp-35d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZn2IpgpMZXTkwbK1HbB0nYoRt29N51gM',
    appId: '1:694288625915:ios:86bd8fe563a7bc201ec05e',
    messagingSenderId: '694288625915',
    projectId: 'quizapp-35d28',
    storageBucket: 'quizapp-35d28.appspot.com',
    iosClientId: '694288625915-0j81mf1vqhqfec34tp912uiffc6eplls.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZn2IpgpMZXTkwbK1HbB0nYoRt29N51gM',
    appId: '1:694288625915:ios:86bd8fe563a7bc201ec05e',
    messagingSenderId: '694288625915',
    projectId: 'quizapp-35d28',
    storageBucket: 'quizapp-35d28.appspot.com',
    iosClientId: '694288625915-0j81mf1vqhqfec34tp912uiffc6eplls.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApplication',
  );
}
